version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./src:/usr/src/app/src   # Mount the source code as a volume
